version: "3.3"
services:
  # database:
  #   image: postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/back4app_test_template
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    # depends_on:
    #   - database
volumes:
  postgres:
  redis:
  bundler_gems:
