version: "3.3"
volumes:
  postgres-data:
    driver: local
  bundler_gems:
services:
  db: # postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/back4app_test_template
      - bundler_gems:/usr/local/bundle/
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    command: >
      bash -c "rm -f tmp/pids/server.pid 
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
