version: "3.3"
volumes:
  db:
  bundler_gems:
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true
  # db: # posgres
  #   image: postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/back4app_test_template
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    command: >
      bash -c "rm -f tmp/pids/server.pid 
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
